In [55]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.pipeline import Pipeline
from xgboost.sklearn import XGBClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.feature_selection import RFE, RFECV
from sklearn.svm import SVC

data = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

data['Family'] = data.SibSp + data.Parch + 1
test['Family'] = test.SibSp + test.Parch + 1

data = data.drop(["Ticket","Parch", "SibSp", "PassengerId"], axis=1)
test = test.drop(["Ticket","Parch", "SibSp"], axis=1)

data.Name = data.Name.str.extract(' ([A-Za-z]+)\.', expand=False)
data.Name = data.Name.replace(['Lady', 'Countess','Capt', 'Col','Don', 'Dr', 'Major', 'Rev', 'Sir', 'Jonkheer', 'Dona'], 0)
data.Name = data.Name.replace(['Mlle','Miss','Ms'], 1)
data.Name = data.Name.replace(['Mme', 'Mrs'],2)
data.Name = data.Name.replace(['Mr', 'Master'],3)

test.Name = test.Name.str.extract(' ([A-Za-z]+)\.', expand=False)
test.Name = test.Name.replace(['Lady', 'Countess','Capt', 'Col','Don', 'Dr', 'Major', 'Rev', 'Sir', 'Jonkheer', 'Dona'], 0)
test.Name = test.Name.replace(['Mlle','Miss','Ms'], 1)
test.Name = test.Name.replace(['Mme', 'Mrs'],2)
test.Name = test.Name.replace(['Mr', 'Master'],3)

data.Sex.replace(["male", "female"], [0,1], inplace = True)
test.Sex.replace(["male", "female"], [0,1], inplace = True)

data.Embarked = data.Embarked.fillna(data.Embarked.mode()[0])
data.Fare = data.Fare.astype(float)
data.Fare = data.Fare.fillna(value = np.mean(data.Fare))
data.Cabin = data.Cabin.str[0]
data.Cabin.fillna('X', inplace = True)
for i in range(0,890):
    if data.loc[i, "Age"] <= 15:
        data.loc[i, "Age"] = 0
    elif data.loc[i, "Age"] >= 60:
        data.loc[i, "Age"] = 2
    else:
        data.loc[i, "Age"] =1

test.Embarked = test.Embarked.fillna(test.Embarked.mode()[0])
test.Fare = test.Fare.astype(float)
test.Fare = test.Fare.fillna(value = np.mean(test.Fare))
test.Cabin = test.Cabin.str[0]
test.Cabin.fillna('X', inplace = True)
for i in range(0,418):
    if test.loc[i, "Age"] <= 15:
        test.loc[i, "Age"] = 0
    elif test.loc[i, "Age"] >= 60:
        test.loc[i, "Age"] = 2
    else:
        test.loc[i, "Age"] =1
        
X = pd.get_dummies(data)
y = data.Survived
X_test = pd.get_dummies(test)
X.drop(["Survived", "Cabin_X", "Embarked_S"], axis=1, inplace=True)
X_test.drop(["Cabin_X", "Embarked_S"], axis=1, inplace=True)


model = make_pipeline(RFECV(RandomForestClassifier(), step=1),
                     RandomForestClassifier())
#model = XGBClassifier()
model.fit(X, y)

submission = pd.DataFrame({
        "PassengerId": X_test["PassengerId"],
        "Survived": model.predict(X_test)
    })
submission.to_csv('submission2.csv', index=False)

In [14]:
data.Age[891]

KeyError: 891

In [9]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.pipeline import Pipeline
from xgboost.sklearn import XGBClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import RFE, RFECV

data = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

data['Family'] = data.SibSp + data.Parch + 1
test['Family'] = test.SibSp + test.Parch + 1

data = data.drop(["Ticket","Parch", "SibSp", "PassengerId"], axis=1)
test = test.drop(["Ticket","Parch", "SibSp"], axis=1)

data.Name = data.Name.str.extract(' ([A-Za-z]+)\.', expand=False)
data.Name = data.Name.replace(['Lady', 'Countess','Capt', 'Col','Don', 'Dr', 'Major', 'Rev', 'Sir', 'Jonkheer', 'Dona'], 0)
data.Name = data.Name.replace(['Mlle','Miss','Ms'], 1)
data.Name = data.Name.replace(['Mme', 'Mrs'],2)
data.Name = data.Name.replace(['Mr', 'Master'],3)

test.Name = test.Name.str.extract(' ([A-Za-z]+)\.', expand=False)
test.Name = test.Name.replace(['Lady', 'Countess','Capt', 'Col','Don', 'Dr', 'Major', 'Rev', 'Sir', 'Jonkheer', 'Dona'], 0)
test.Name = test.Name.replace(['Mlle','Miss','Ms'], 1)
test.Name = test.Name.replace(['Mme', 'Mrs'],2)
test.Name = test.Name.replace(['Mr', 'Master'],3)

data.Sex.replace(["male", "female"], [0,1], inplace = True)
test.Sex.replace(["male", "female"], [0,1], inplace = True)

data.Embarked = data.Embarked.fillna(data.Embarked.mode()[0])
data.Fare = data.Fare.astype(float)
data.Fare = data.Fare.fillna(value = np.mean(data.Fare))
data.Cabin = data.Cabin.str[0]
data.Cabin.fillna('X', inplace = True)
data.Age.fillna('-1', inplace = True)
data.Age = data.Age.astype(float)

test.Embarked = test.Embarked.fillna(test.Embarked.mode()[0])
test.Fare = test.Fare.astype(float)
test.Fare = test.Fare.fillna(value = np.mean(test.Fare))
test.Cabin = test.Cabin.str[0]
test.Cabin.fillna('X', inplace = True)
test.Age.fillna('-1', inplace = True)
test.Age = test.Age.astype(float)

X = pd.get_dummies(data)
y = data.Survived
X_test = pd.get_dummies(test)

X.drop(["Survived", "Cabin_X", "Embarked_S"], axis=1, inplace=True)
X_test.drop(["Cabin_X", "Embarked_S"], axis=1, inplace=True)

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

selector = SelectFromModel(LogisticRegression(), 0.2)
selector.fit(X_train, y_train)
selector.transform(X_train)

array([[ 0.825616  , -0.40850773,  1.35941164, ...,  0.06368307,
        -0.19853478, -0.13093073],
       [-1.54948943, -1.52290431,  1.35941164, ..., -0.55744499,
        -0.19853478, -0.13093073],
       [ 0.825616  ,  0.70588884, -0.73561236, ..., -0.55744499,
        -0.19853478, -0.13093073],
       ...,
       [ 0.825616  ,  0.70588884, -0.73561236, ...,  2.54819534,
        -0.19853478, -0.13093073],
       [ 0.825616  , -0.40850773,  1.35941164, ...,  0.68481114,
        -0.19853478, -0.13093073],
       [-1.54948943,  0.70588884, -0.73561236, ..., -0.55744499,
         5.03690087, -0.13093073]])

In [3]:
selector.get_support()

array([ True, False,  True,  True, False,  True, False, False, False,
       False, False, False, False, False, False, False])

In [12]:
model = RandomForestClassifier()
model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score
accuracy_score(model.predict(X_test),y_test)

0.7988826815642458

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

from sklearn.feature_selection import RFE, RFECV
model = make_pipeline(RFECV(RandomForestClassifier(), step=1),
                      RandomForestClassifier())
model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score
accuracy_score(model.predict(X_test),y_test)

0.7988826815642458

In [56]:
submission2 = pd.read_csv("submission2.csv")
submission1 = pd.read_csv("submission.csv")

In [15]:
gender[submission.PassengerId == gender.PassengerId]

NameError: name 'gender' is not defined

In [61]:
gender = pd.read_csv("gender_submission.csv")
gender[gender.Survived == 1]

     PassengerId  Survived
1            893         1
4            896         1
6            898         1
8            900         1
12           904         1
14           906         1
15           907         1
18           910         1
19           911         1
22           914         1
24           916         1
26           918         1
32           924         1
33           925         1
36           928         1
37           929         1
43           935         1
44           936         1
48           940         1
49           941         1
52           944         1
53           945         1
59           951         1
63           955         1
65           957         1
66           958         1
69           961         1
70           962         1
72           964         1
74           966         1
..           ...       ...
347         1239         1
349         1241         1
350         1242         1
354         1246         1
356         1248         1
359         1251         1
361         1253         1
362         1254         1
364         1256         1
365         1257         1
367         1259         1
368         1260         1
371         1263         1
374         1266         1
375         1267         1
376         1268         1
382         1274         1
383         1275         1
385         1277         1
391         1283         1
395         1287         1
397         1289         1
400         1292         1
402         1294         1
408         1300         1
409         1301         1
410         1302         1
411         1303         1
412         1304         1
414         1306         1

[152 rows x 2 columns]

In [57]:
submission2.Survived.value_counts()

0    409
1      9
Name: Survived, dtype: int64

In [48]:
submission1.Survived.value_counts()

0    336
1     82
Name: Survived, dtype: int64